### PR TITLE
Found another wrong get Call

### PR DESCRIPTION
**Pull request by DxsSucuk**
Fixed another wrong get Call.

### CODE REVIEW

**Comment by ByteDream** [comment]
Ty, hopefully this was the last one xD

**Comment by DxsSucuk** [comment]
I hope to haha.

Just found them because I was working on a OpenSource Project myself for my School so people can get notified on Discord if a Lesson is replaced with another or if you have a free "block".

**Comment by ByteDream** [comment]
I've created the library for the exact same reason.
But if you look at my bots' [source code](https://github.com/ByteDream/untisbot-discord) (especially [this file](https://github.com/ByteDream/untisbot-discord/blob/master/src/org/bytedream/untisbot/discord/DiscordCommandListener.java)) you may see why I stopped developing it xD

**Comment by DxsSucuk** [comment]
I would start rewritting it with my own BotBase that i use for my Bot Ree6 which is a huge mess aswell. And maybe create a Pull-Request in the next days to update the Original Repository.

**Pull request merged**
